import type {
  ActionSpec,
  AreaSpec,
  AttackStyleDefinition,
  ChargeSpec,
  ComboSpec,
  ComboStageSpec,
  CostSpec,
  GuardSpec,
  HitShape,
  HitscanSpec,
  LungeSpec,
  MovementSpec,
  MultihitSpec,
  PlacedSpec,
  ProjectileSpec,
  SummonSpec,
} from './actionSpec';

// 攻撃スタイルカタログ(F11)。数値はすべて調整可の初期値。ID・系統・押下・長押し・コストは F11 の表と一致させる。

const NONE: CostSpec = { type: 'none' };
const stamina = (amount: number): CostSpec => ({ type: 'stamina', amount });
const energy = (amount: number): CostSpec => ({ type: 'energy', amount });
const staminaPerSec = (rate: number): CostSpec => ({ type: 'staminaPerSecond', rate });
const energyPerSec = (rate: number): CostSpec => ({ type: 'energyPerSecond', rate });

const sphere = (radius: number, forward = 1.0): HitShape => ({ type: 'sphere', radius, forward });
const fan = (radius: number, angleDeg: number): HitShape => ({ type: 'fan', radius, angleDeg });
const ring = (radius: number, width = 0.8): HitShape => ({ type: 'ring', radius, width });
const line = (length: number, width: number): HitShape => ({ type: 'line', length, width });

const stage = (
  damage: number,
  startup: number,
  active: number,
  total: number,
  advance = 0.3,
): ComboStageSpec => ({
  damage,
  startup,
  active,
  total,
  advance,
});

const MELEE_TARGET = { halfAngleDeg: 30, range: 3.0 };

function combo(
  stages: readonly ComboStageSpec[],
  opts: Partial<Omit<ComboSpec, 'kind' | 'stages'>> = {},
): ComboSpec {
  return {
    kind: 'combo',
    stages,
    shape: sphere(1.2),
    comboWindow: 0.8,
    hitClass: 'light',
    knockback: 1.7,
    energyPerHit: 5,
    target: MELEE_TARGET,
    keepMoving: false,
    airUses: 1,
    ...opts,
  };
}

function lunge(damage: number, opts: Partial<Omit<LungeSpec, 'kind' | 'damage'>> = {}): LungeSpec {
  return {
    kind: 'lunge',
    damage,
    startup: 0.1,
    active: 0.15,
    total: 0.7,
    shape: sphere(1.5),
    lungeSpeed: 9.0,
    lungeMaxTime: 0.35,
    stopDistance: 1.0,
    target: { halfAngleDeg: 45, range: 6.0 },
    knockback: 5.0,
    hitClass: 'heavy',
    energyPerHit: 10,
    hitWhileMoving: false,
    ...opts,
  };
}

function hitscan(
  damage: number,
  range: number,
  total: number,
  opts: Partial<Omit<HitscanSpec, 'kind' | 'damage' | 'range' | 'total'>> = {},
): HitscanSpec {
  return {
    kind: 'hitscan',
    damage,
    range,
    startup: 0.05,
    total,
    rays: 1,
    spreadDeg: 0,
    pierce: false,
    target: { halfAngleDeg: 15, range },
    knockback: 1.0,
    hitClass: 'light',
    energyPerHit: 3,
    airborne: true,
    beamWidth: 0,
    ...opts,
  };
}

function charge(
  maxTime: number,
  release: ActionSpec,
  scale: ChargeSpec['scale'],
  opts: Partial<Omit<ChargeSpec, 'kind' | 'maxTime' | 'release' | 'scale'>> = {},
): ChargeSpec {
  return { kind: 'charge', maxTime, moveSpeed: 1.8, release, scale, ...opts };
}

function area(
  damage: number,
  shape: HitShape,
  opts: Partial<Omit<AreaSpec, 'kind' | 'damage' | 'shape'>> = {},
): AreaSpec {
  return {
    kind: 'area',
    damage,
    shape,
    startup: 0.2,
    active: 0.1,
    total: 0.7,
    knockback: 3.0,
    hitClass: 'medium',
    energyPerHit: 5,
    movement: 'stop',
    ...opts,
  };
}

function multihit(
  damage: number,
  interval: number,
  count: number,
  opts: Partial<Omit<MultihitSpec, 'kind' | 'damage' | 'interval' | 'count'>> = {},
): MultihitSpec {
  return {
    kind: 'multihit',
    damage,
    interval,
    count,
    shape: sphere(1.2),
    moveSpeed: 0,
    hitClass: 'light',
    knockback: 0.5,
    energyPerHit: 2,
    whileHeld: false,
    maxDuration: interval * count,
    ...opts,
  };
}

function projectile(
  damage: number,
  speed: number,
  range: number,
  opts: Partial<Omit<ProjectileSpec, 'kind' | 'damage' | 'speed' | 'range'>> = {},
): ProjectileSpec {
  return {
    kind: 'projectile',
    damage,
    speed,
    range,
    count: 1,
    spreadDeg: 0,
    interval: 0,
    gravity: false,
    homing: false,
    returning: false,
    bounces: 0,
    pierce: false,
    radius: 0.25,
    hitClass: 'light',
    knockback: 1.0,
    energyPerHit: 3,
    target: { halfAngleDeg: 15, range },
    startup: 0.1,
    total: 0.4,
    airborne: true,
    ...opts,
  };
}

function placed(
  object: PlacedSpec['object'],
  opts: Partial<Omit<PlacedSpec, 'kind' | 'object'>> = {},
): PlacedSpec {
  return {
    kind: 'placed',
    object,
    lifetime: 10,
    radius: 1.5,
    damage: 30,
    interval: 0,
    delay: 0,
    maxCount: 3,
    forward: 0,
    hitClass: 'medium',
    knockback: 3.0,
    energyPerHit: 5,
    count: 1,
    spreadDeg: 0,
    ...opts,
  };
}

function summon(
  entity: SummonSpec['entity'],
  opts: Partial<Omit<SummonSpec, 'kind' | 'entity'>> = {},
): SummonSpec {
  return {
    kind: 'summon',
    entity,
    count: 1,
    lifetime: 10,
    damage: 8,
    interval: 1.5,
    range: 8,
    hitClass: 'light',
    energyPerHit: 2,
    ...opts,
  };
}

function guard(opts: Partial<Omit<GuardSpec, 'kind'>> = {}): GuardSpec {
  return {
    kind: 'guard',
    window: 0.5,
    angleDeg: 120,
    reduction: 1,
    onSuccess: 'counter',
    counterDamage: 40,
    toppleSeconds: 0,
    failRecovery: 0.5,
    staminaPerSecond: 0,
    moveSpeed: 0,
    autoRiposte: false,
    ...opts,
  };
}

function movement(
  move: MovementSpec['move'],
  requires: MovementSpec['requires'],
  opts: Partial<Omit<MovementSpec, 'kind' | 'move' | 'requires'>> = {},
): MovementSpec {
  return {
    kind: 'movement',
    move,
    requires,
    distance: 3,
    speed: 9,
    height: 0,
    invincible: 0,
    then: null,
    windowSeconds: 0.3,
    ...opts,
  };
}

type Def = Omit<AttackStyleDefinition, 'hold'> & { readonly hold: AttackStyleDefinition['hold'] };
const def = (d: Def): AttackStyleDefinition => d;
const holdStart = (action: ActionSpec) => ({ trigger: 'start' as const, action });
const holdRelease = (action: ActionSpec) => ({ trigger: 'release' as const, action });

// 既定の格闘・銃撃(F04 の正典と一致)
const MELEE_COMBO = combo(
  [stage(10, 0.1, 0.1, 0.4, 0.3), stage(10, 0.1, 0.1, 0.4, 0.3), stage(15, 0.15, 0.15, 0.6, 0.5)],
  { kinds: ['normal1', 'normal2', 'normal3'] },
);
const GUN_SHOT = hitscan(8, 12, 0.25, { attackKind: 'shoot' });
const GUN_CHARGED = charge(
  1.0,
  hitscan(20, 16, 0.5, {
    pierce: true,
    knockback: 3.0,
    hitClass: 'medium',
    energyPerHit: 10,
    attackKind: 'chargedShot',
  }),
  { damage: [20, 60] },
);

export const ATTACK_STYLES: readonly AttackStyleDefinition[] = [
  // ---- A 剣術
  def({
    id: 'melee',
    name: '格闘',
    category: 'sword',
    description: '通常攻撃 3 段コンボ。長押しで敵へ踏み込む接近強攻撃',
    press: MELEE_COMBO,
    hold: holdStart(lunge(35, { attackKind: 'strongAttack' })),
    cost: { press: NONE, hold: stamina(25) },
    mechanisms: ['A1', 'A2'],
    scale: 'S',
  }),
  def({
    id: 'dual_blade',
    name: '二刀流',
    category: 'sword',
    description: '高速 5 段コンボ。長押しで乱舞',
    press: combo(
      [
        stage(6, 0.06, 0.08, 0.25, 0.2),
        stage(6, 0.06, 0.08, 0.25, 0.2),
        stage(6, 0.06, 0.08, 0.25, 0.2),
        stage(6, 0.06, 0.08, 0.25, 0.2),
        stage(12, 0.1, 0.1, 0.35, 0.2),
      ],
      { shape: sphere(1.0) },
    ),
    hold: holdStart(multihit(6, 0.15, 8, { shape: sphere(1.2) })),
    cost: { press: NONE, hold: stamina(20) },
    mechanisms: ['A1', 'N2'],
    scale: 'M',
  }),
  def({
    id: 'greatsword',
    name: '大剣',
    category: 'sword',
    description: '重い 2 段。長押しで溜め斬り',
    press: combo([stage(20, 0.2, 0.15, 0.7, 0.3), stage(30, 0.25, 0.2, 0.9, 0.4)], {
      hitClass: 'heavy',
      knockback: 4.0,
      shape: sphere(1.5),
    }),
    hold: holdRelease(
      charge(1.0, area(30, sphere(1.8), { hitClass: 'heavy', knockback: 4.0, energyPerHit: 10 }), {
        damage: [30, 80],
      }),
    ),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['A1', 'A4'],
    scale: 'S',
  }),
  def({
    id: 'iai',
    name: '居合',
    category: 'sword',
    description: '通常斬り 2 段。構えて離すと前方 3 m を貫く抜刀',
    press: combo([stage(12, 0.1, 0.1, 0.4), stage(12, 0.1, 0.1, 0.4)]),
    hold: holdRelease(
      charge(
        1.0,
        area(45, line(3.0, 1.0), {
          hitClass: 'heavy',
          knockback: 2.0,
          energyPerHit: 10,
          startup: 0.05,
          active: 0.1,
          total: 0.5,
        }),
        { damage: [45, 45] },
        { moveSpeed: 0 },
      ),
    ),
    cost: { press: NONE, hold: stamina(15) },
    mechanisms: ['A4', 'A3'],
    scale: 'S',
  }),
  def({
    id: 'rapier',
    name: '刺突剣',
    category: 'sword',
    description: '直線の突き。長押しで連続突き',
    press: combo([stage(9, 0.08, 0.1, 0.35, 0.2)], { shape: line(1.6, 1.0), comboWindow: 0.5 }),
    hold: holdStart(multihit(5, 0.1, 8, { shape: line(1.6, 1.0) })),
    cost: { press: NONE, hold: stamina(10) },
    mechanisms: ['A1', 'N2'],
    scale: 'M',
  }),
  def({
    id: 'spin_slash',
    name: '回転斬り',
    category: 'sword',
    description: '周囲 360 度の斬り。長押しで回転しながら移動',
    press: area(8, ring(1.5, 1.5), {
      startup: 0.1,
      active: 0.1,
      total: 0.5,
      knockback: 2.0,
      hitClass: 'light',
    }),
    hold: holdStart(
      multihit(8, 0.25, 6, {
        shape: ring(1.5, 1.5),
        moveSpeed: 1.8,
        whileHeld: true,
        maxDuration: 1.5,
      }),
    ),
    cost: { press: NONE, hold: staminaPerSec(6) },
    mechanisms: ['A5', 'N2'],
    scale: 'M',
  }),
  def({
    id: 'counter_blade',
    name: 'カウンター剣',
    category: 'sword',
    description: '通常斬り 2 段。長押しで受けの構え、被弾を無効化して反撃',
    press: combo([stage(10, 0.1, 0.1, 0.4), stage(15, 0.15, 0.15, 0.6, 0.5)]),
    hold: holdStart(guard({ window: 0.5, counterDamage: 40 })),
    cost: { press: NONE, hold: stamina(15) },
    mechanisms: ['A1', 'N5'],
    scale: 'L',
  }),
  def({
    id: 'charge_slash',
    name: '突進斬り',
    category: 'sword',
    description: '通常斬り 1 段。長押しで 6 m を駆け抜けて斬る',
    press: combo([stage(12, 0.1, 0.1, 0.4)]),
    hold: holdStart(
      lunge(25, {
        lungeSpeed: 12,
        lungeMaxTime: 0.5,
        stopDistance: 0,
        target: null,
        hitWhileMoving: true,
        shape: sphere(1.2, 0.5),
      }),
    ),
    cost: { press: NONE, hold: stamina(30) },
    mechanisms: ['A2'],
    scale: 'S',
  }),
  def({
    id: 'aerial_blade',
    name: '空中剣士',
    category: 'sword',
    description: '地上は 2 段、空中攻撃が 3 回。空中で長押しすると急降下斬り',
    press: combo([stage(10, 0.1, 0.1, 0.4), stage(10, 0.1, 0.1, 0.4)], { airUses: 3 }),
    hold: holdStart(
      movement('dive', 'airborne', {
        fallSpeed: 15,
        then: area(30, sphere(2.0, 0), { hitClass: 'heavy', knockback: 4.0 }),
      }),
    ),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['A6', 'N7'],
    scale: 'M',
  }),
  def({
    id: 'sword_wave',
    name: '剣気',
    category: 'sword',
    description: '斬撃波を 6 m 飛ばす。長押しで射程と威力を上げる大剣気',
    press: projectile(10, 15, 6, { radius: 0.5 }),
    hold: holdRelease(
      charge(
        1.0,
        projectile(20, 15, 6, { radius: 0.6, pierce: true, hitClass: 'medium', energyPerHit: 8 }),
        { damage: [20, 50], range: [6, 12] },
      ),
    ),
    cost: { press: energy(5), hold: NONE },
    mechanisms: ['N1', 'A4'],
    scale: 'M',
  }),
  // ---- B 打撃
  def({
    id: 'boxer',
    name: '拳闘',
    category: 'strike',
    description: '素早い 4 段。長押しで踏み込みの強打',
    press: combo(
      [
        stage(6, 0.06, 0.08, 0.25, 0.2),
        stage(6, 0.06, 0.08, 0.25, 0.2),
        stage(6, 0.06, 0.08, 0.25, 0.2),
        stage(12, 0.1, 0.1, 0.35, 0.2),
      ],
      { shape: sphere(0.9, 0.8) },
    ),
    hold: holdStart(lunge(30, { lungeMaxTime: 0.17, knockback: 6.0, shape: sphere(1.0, 0.8) })),
    cost: { press: NONE, hold: stamina(20) },
    mechanisms: ['A1', 'A2'],
    scale: 'S',
  }),
  def({
    id: 'warhammer',
    name: '大槌',
    category: 'strike',
    description: '遅い 1 段。長押しで着弾点に衝撃の振り下ろし',
    press: combo([stage(35, 0.35, 0.15, 1.0, 0.3)], {
      hitClass: 'heavy',
      knockback: 6.0,
      shape: sphere(1.3),
    }),
    hold: holdStart(
      area(50, sphere(2.0, 1.5), {
        startup: 0.5,
        active: 0.15,
        total: 1.2,
        knockback: 6.0,
        hitClass: 'huge',
        energyPerHit: 10,
      }),
    ),
    cost: { press: NONE, hold: stamina(30) },
    mechanisms: ['A1', 'A5'],
    scale: 'S',
  }),
  def({
    id: 'staff',
    name: '棍術',
    category: 'strike',
    description: '扇形の薙ぎ。長押しで連続回転',
    press: area(10, fan(1.6, 150), {
      startup: 0.12,
      active: 0.12,
      total: 0.5,
      knockback: 2.0,
      hitClass: 'light',
    }),
    hold: holdStart(multihit(10, 0.2, 5, { shape: ring(1.6, 1.6) })),
    cost: { press: NONE, hold: stamina(15) },
    mechanisms: ['A5', 'N2'],
    scale: 'M',
  }),
  def({
    id: 'palm',
    name: '掌底',
    category: 'strike',
    description: '1 段 + 強いノックバック。長押しで震脚',
    press: combo([stage(8, 0.08, 0.1, 0.4, 0.2)], { knockback: 5.0, shape: sphere(1.0, 0.8) }),
    hold: holdStart(
      area(15, sphere(2.5, 0), {
        knockback: 8.0,
        hitClass: 'heavy',
        startup: 0.25,
        active: 0.1,
        total: 0.8,
      }),
    ),
    cost: { press: NONE, hold: stamina(20) },
    mechanisms: ['A1', 'A5'],
    scale: 'S',
  }),
  def({
    id: 'kicker',
    name: '蹴り',
    category: 'strike',
    description: '移動しながらの前蹴り。長押しで回し蹴り',
    press: combo([stage(12, 0.1, 0.1, 0.4, 0.2)], { keepMoving: true, shape: sphere(1.0, 0.9) }),
    hold: holdStart(
      area(25, ring(1.8, 1.8), {
        knockback: 4.0,
        hitClass: 'medium',
        startup: 0.2,
        active: 0.15,
        total: 0.7,
      }),
    ),
    cost: { press: NONE, hold: stamina(15) },
    mechanisms: ['A1', 'A5'],
    scale: 'S',
  }),
  def({
    id: 'ground_slam',
    name: '地割り',
    category: 'strike',
    description: '1 段。長押しでジャンプして落下、着地点から扇形の衝撃',
    press: combo([stage(10, 0.1, 0.1, 0.4)]),
    hold: holdStart(
      area(40, fan(3.0, 90), {
        jumpHeight: 1.5,
        startup: 0.5,
        active: 0.15,
        total: 1.0,
        knockback: 5.0,
        hitClass: 'heavy',
        energyPerHit: 10,
      }),
    ),
    cost: { press: NONE, hold: stamina(25) },
    mechanisms: ['A5', 'N7'],
    scale: 'M',
  }),
  def({
    id: 'rapid_fist',
    name: '連打',
    category: 'strike',
    description: '1 段。長押し中は連続で殴り続ける',
    press: combo([stage(5, 0.05, 0.08, 0.25, 0.1)], { shape: sphere(0.9, 0.8) }),
    hold: holdStart(
      multihit(4, 0.08, 40, { shape: sphere(0.9, 0.8), whileHeld: true, maxDuration: 3 }),
    ),
    cost: { press: NONE, hold: staminaPerSec(8) },
    mechanisms: ['N2'],
    scale: 'M',
  }),
  def({
    id: 'grappler',
    name: '投げ',
    category: 'strike',
    description: '掴んで投げる。長押しで遠くへ投げ飛ばす',
    press: {
      kind: 'pull',
      radius: 1.2,
      speed: 0,
      stopDistance: 0.8,
      holdSeconds: 0.5,
      reach: 1.2,
      damage: 30,
      hitClass: 'heavy',
      energyPerHit: 8,
      then: null,
    },
    hold: holdStart({
      kind: 'pull',
      radius: 1.2,
      speed: 0,
      stopDistance: 0.8,
      holdSeconds: 0.5,
      reach: 1.2,
      damage: 20,
      hitClass: 'heavy',
      energyPerHit: 8,
      then: area(20, sphere(1.5, 4.0), {
        startup: 0.3,
        active: 0.1,
        total: 0.6,
        hitClass: 'medium',
      }),
    }),
    cost: { press: NONE, hold: stamina(20) },
    mechanisms: ['N9', 'A5'],
    scale: 'L',
  }),
  def({
    id: 'shield_bash',
    name: '盾殴り',
    category: 'strike',
    description: '盾で殴る。長押しで構え、離すと盾突進',
    press: combo([stage(8, 0.1, 0.1, 0.4, 0.2)], { knockback: 3.0, shape: sphere(1.0, 0.8) }),
    hold: holdStart(
      guard({
        window: 3.0,
        angleDeg: 120,
        reduction: 1,
        onSuccess: 'none',
        moveSpeed: 1.8,
        release: lunge(20, {
          lungeMaxTime: 0.22,
          target: null,
          hitWhileMoving: true,
          shape: sphere(1.0, 0.6),
        }),
      }),
    ),
    cost: { press: NONE, hold: stamina(15) },
    mechanisms: ['N5', 'A2'],
    scale: 'L',
  }),
  def({
    id: 'iron_shoulder',
    name: '鉄山靠',
    category: 'strike',
    description: '体当たり。長押しで溜めて大きく体当たり',
    press: lunge(15, {
      lungeMaxTime: 0.11,
      startup: 0.05,
      active: 0.1,
      total: 0.5,
      knockback: 4.0,
      hitClass: 'medium',
      energyPerHit: 5,
      shape: sphere(1.0, 0.6),
    }),
    hold: holdStart(
      lunge(40, {
        lungeMaxTime: 0.33,
        startup: 0.6,
        knockback: 7.0,
        hitClass: 'huge',
        hitWhileMoving: true,
        shape: sphere(1.1, 0.6),
        target: null,
      }),
    ),
    cost: { press: NONE, hold: stamina(25) },
    mechanisms: ['A2'],
    scale: 'S',
  }),
  // ---- C 長柄
  def({
    id: 'spear',
    name: '槍',
    category: 'polearm',
    description: 'リーチの長い突き 3 段。長押しで貫く踏み込み突き',
    press: combo(
      [stage(9, 0.1, 0.1, 0.4, 0.2), stage(9, 0.1, 0.1, 0.4, 0.2), stage(14, 0.15, 0.15, 0.6, 0.3)],
      { shape: sphere(0.6, 2.0), knockback: 1.0 },
    ),
    hold: holdStart(lunge(30, { shape: line(2.0, 1.0), hitWhileMoving: false })),
    cost: { press: NONE, hold: stamina(20) },
    mechanisms: ['A1', 'A2'],
    scale: 'S',
  }),
  def({
    id: 'naginata',
    name: '薙刀',
    category: 'polearm',
    description: '横薙ぎ 2 段。長押しで大回転',
    press: combo([stage(12, 0.12, 0.12, 0.5), stage(16, 0.15, 0.15, 0.6)], {
      shape: fan(2.0, 180),
      hitClass: 'medium',
    }),
    hold: holdStart(
      area(35, ring(2.5, 2.5), {
        hitClass: 'heavy',
        knockback: 4.0,
        startup: 0.3,
        active: 0.15,
        total: 0.9,
      }),
    ),
    cost: { press: NONE, hold: stamina(25) },
    mechanisms: ['A5'],
    scale: 'S',
  }),
  def({
    id: 'lance',
    name: '突撃槍',
    category: 'polearm',
    description: '突き 1 段。長押しでタメて突撃',
    press: combo([stage(12, 0.1, 0.1, 0.45, 0.2)], { shape: sphere(0.6, 2.0) }),
    hold: holdRelease(
      charge(
        1.0,
        lunge(25, {
          lungeSpeed: 12,
          lungeMaxTime: 0.25,
          target: null,
          hitWhileMoving: true,
          shape: sphere(0.9, 0.8),
          hitClass: 'heavy',
        }),
        { damage: [25, 60], distance: [3, 8] },
      ),
    ),
    cost: { press: NONE, hold: stamina(30) },
    mechanisms: ['A2', 'A4'],
    scale: 'M',
  }),
  def({
    id: 'javelin',
    name: '投槍',
    category: 'polearm',
    description: '突き 2 段。長押しで槍を投げる',
    press: combo([stage(10, 0.1, 0.1, 0.4, 0.2), stage(10, 0.1, 0.1, 0.4, 0.2)], {
      shape: sphere(0.6, 2.0),
    }),
    hold: holdStart(
      projectile(35, 14, 14, {
        gravity: true,
        radius: 0.3,
        hitClass: 'heavy',
        knockback: 3.0,
        energyPerHit: 10,
        airborne: false,
      }),
    ),
    cost: { press: NONE, hold: stamina(10) },
    mechanisms: ['N1'],
    scale: 'M',
  }),
  def({
    id: 'pole_vault',
    name: '棒高跳び',
    category: 'polearm',
    description: '突き 2 段。長押しで棒を使って跳躍し、着地で衝撃',
    press: combo([stage(10, 0.1, 0.1, 0.4, 0.2), stage(10, 0.1, 0.1, 0.4, 0.2)], {
      shape: sphere(0.6, 2.0),
    }),
    hold: holdStart(
      movement('poleVault', 'any', {
        height: 4.0,
        then: area(20, sphere(1.5, 0), { hitClass: 'medium' }),
      }),
    ),
    cost: { press: NONE, hold: stamina(20) },
    mechanisms: ['N7', 'A5'],
    scale: 'M',
  }),
  def({
    id: 'whirlwind',
    name: '旋風薙ぎ',
    category: 'polearm',
    description: '薙ぎ 1 段。長押しで走りながら回転',
    press: area(10, fan(2.0, 180), { startup: 0.12, active: 0.12, total: 0.5, hitClass: 'light' }),
    hold: holdStart(
      multihit(10, 0.3, 5, {
        shape: ring(2.0, 2.0),
        moveSpeed: 4.5,
        whileHeld: true,
        maxDuration: 1.5,
      }),
    ),
    cost: { press: NONE, hold: staminaPerSec(8) },
    mechanisms: ['A5', 'N2'],
    scale: 'M',
  }),
  def({
    id: 'skewer',
    name: '串刺し',
    category: 'polearm',
    description: '突き 2 段。長押しで前方の直線上をまとめて貫く',
    press: combo([stage(10, 0.1, 0.1, 0.4, 0.2), stage(12, 0.12, 0.12, 0.5, 0.2)], {
      shape: sphere(0.6, 2.0),
    }),
    hold: holdStart(
      area(30, line(4.0, 0.8), {
        startup: 0.25,
        active: 0.1,
        total: 0.8,
        hitClass: 'heavy',
        knockback: 2.0,
        energyPerHit: 10,
      }),
    ),
    cost: { press: NONE, hold: stamina(20) },
    mechanisms: ['A3'],
    scale: 'S',
  }),
  def({
    id: 'halberd',
    name: '斧槍',
    category: 'polearm',
    description: '縦斬り。長押しで敵を手元へ引き寄せて斬る',
    press: combo([stage(18, 0.2, 0.15, 0.6, 0.3)], { hitClass: 'medium', shape: sphere(1.3, 1.2) }),
    hold: holdStart({
      kind: 'pull',
      radius: 3.0,
      speed: 5.0,
      stopDistance: 1.0,
      holdSeconds: 0,
      reach: 3.0,
      damage: 0,
      hitClass: 'medium',
      energyPerHit: 0,
      then: combo([stage(25, 0.1, 0.15, 0.6, 0)], { hitClass: 'heavy' }),
    }),
    cost: { press: NONE, hold: stamina(25) },
    mechanisms: ['A1', 'N9'],
    scale: 'L',
  }),
  def({
    id: 'twin_spear',
    name: '双槍',
    category: 'polearm',
    description: '左右交互の 4 段。長押しで 3 連続の突き',
    press: combo(
      [
        stage(8, 0.08, 0.1, 0.3, 0.2),
        stage(8, 0.08, 0.1, 0.3, 0.2),
        stage(8, 0.08, 0.1, 0.3, 0.2),
        stage(14, 0.12, 0.12, 0.5, 0.3),
      ],
      { shape: sphere(0.6, 1.8) },
    ),
    hold: holdStart(multihit(12, 0.15, 3, { shape: sphere(0.7, 2.5) })),
    cost: { press: NONE, hold: stamina(15) },
    mechanisms: ['A1', 'N2'],
    scale: 'M',
  }),
  def({
    id: 'scythe',
    name: '鎌',
    category: 'polearm',
    description: '大きな横薙ぎ。長押しで敵を引き寄せて斬る',
    press: area(16, fan(2.2, 200), { startup: 0.2, active: 0.12, total: 0.7, hitClass: 'medium' }),
    hold: holdStart({
      kind: 'pull',
      radius: 3.0,
      speed: 6.0,
      stopDistance: 1.0,
      holdSeconds: 0,
      reach: 3.0,
      damage: 0,
      hitClass: 'medium',
      energyPerHit: 0,
      then: area(30, fan(2.2, 200), { startup: 0.1, active: 0.12, total: 0.6, hitClass: 'heavy' }),
    }),
    cost: { press: NONE, hold: stamina(25) },
    mechanisms: ['A5', 'N9'],
    scale: 'L',
  }),
  // ---- D 銃火器
  def({
    id: 'gun',
    name: '銃撃',
    category: 'firearm',
    description: '射撃。長押しでタメ、離すと貫通のタメ打ち',
    press: GUN_SHOT,
    hold: holdRelease(GUN_CHARGED),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['A3', 'A4'],
    scale: 'S',
  }),
  def({
    id: 'shotgun',
    name: 'ショットガン',
    category: 'firearm',
    description: '5 本の散弾。長押しで 1 本のスラッグ',
    press: hitscan(5, 6, 0.6, { rays: 5, spreadDeg: 12 }),
    hold: holdRelease(
      charge(1.0, hitscan(40, 10, 0.6, { hitClass: 'heavy', knockback: 4.0, energyPerHit: 10 }), {
        damage: [40, 40],
      }),
    ),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['A3', 'A4'],
    scale: 'S',
  }),
  def({
    id: 'rifle',
    name: 'ライフル',
    category: 'firearm',
    description: '単発の高威力。長押しで精密射撃',
    press: hitscan(20, 20, 0.6, { hitClass: 'medium' }),
    hold: holdRelease(
      charge(
        1.0,
        hitscan(50, 20, 0.6, {
          target: { halfAngleDeg: 5, range: 20 },
          hitClass: 'heavy',
          energyPerHit: 10,
        }),
        { damage: [50, 50] },
      ),
    ),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['A3', 'A4'],
    scale: 'S',
  }),
  def({
    id: 'smg',
    name: 'サブマシンガン',
    category: 'firearm',
    description: '連射。長押しでフルオート',
    press: hitscan(4, 10, 0.1, { target: { halfAngleDeg: 20, range: 10 }, energyPerHit: 1 }),
    hold: holdStart(
      multihit(4, 0.08, 999, {
        whileHeld: true,
        maxDuration: 30,
        ranged: { range: 10, pierce: false, beamWidth: 0 },
        energyPerHit: 1,
      }),
    ),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['A3', 'N2'],
    scale: 'M',
  }),
  def({
    id: 'gatling',
    name: 'ガトリング',
    category: 'firearm',
    description: '短い連射。長押しで回転数が上がる',
    press: hitscan(3, 10, 0.3, { burst: { count: 3, interval: 0.08 }, energyPerHit: 1 }),
    hold: holdStart(
      multihit(3, 0.3, 999, {
        whileHeld: true,
        maxDuration: 30,
        accelerateTo: 0.05,
        ranged: { range: 10, pierce: false, beamWidth: 0 },
        energyPerHit: 1,
      }),
    ),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['A3', 'N2'],
    scale: 'M',
  }),
  def({
    id: 'sniper',
    name: 'スナイパー',
    category: 'firearm',
    description: '単発の長射程。長押しで狙撃',
    press: hitscan(30, 30, 1.0, { hitClass: 'medium', energyPerHit: 5 }),
    hold: holdRelease(
      charge(
        1.5,
        hitscan(120, 30, 1.0, { hitClass: 'huge', knockback: 4.0, energyPerHit: 15 }),
        { damage: [120, 120] },
        { moveSpeed: 0, cameraDistance: 2.0 },
      ),
    ),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['A3', 'A4'],
    scale: 'S',
  }),
  def({
    id: 'revolver',
    name: 'リボルバー',
    category: 'firearm',
    description: '6 発装填。長押しで残弾を一気に撃つファニング',
    press: hitscan(15, 14, 0.3, { ammo: { capacity: 6, reloadTime: 1.2 }, hitClass: 'medium' }),
    hold: holdStart(
      multihit(15, 0.1, 6, {
        ranged: { range: 14, pierce: false, beamWidth: 0 },
        hitClass: 'medium',
        energyPerHit: 3,
      }),
    ),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['A3', 'N2'],
    scale: 'M',
  }),
  def({
    id: 'dual_pistol',
    name: '二丁拳銃',
    category: 'firearm',
    description: '左右交互の射撃。長押しで 2 体同時ロック',
    press: hitscan(6, 12, 0.12, { energyPerHit: 2 }),
    hold: holdStart(
      hitscan(20, 12, 0.5, {
        multiTarget: 2,
        target: { halfAngleDeg: 30, range: 12 },
        hitClass: 'medium',
        energyPerHit: 5,
      }),
    ),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['A3'],
    scale: 'S',
  }),
  def({
    id: 'laser',
    name: 'レーザー',
    category: 'firearm',
    description: '短いビーム。長押しで持続ビーム',
    press: hitscan(6, 10, 0.2, { pierce: true, beamWidth: 0.2 }),
    hold: holdStart(
      multihit(3, 0.1, 30, {
        whileHeld: true,
        maxDuration: 3,
        ranged: { range: 10, pierce: true, beamWidth: 0.2 },
        energyPerHit: 1,
      }),
    ),
    cost: { press: NONE, hold: energyPerSec(2) },
    mechanisms: ['A3', 'N2'],
    scale: 'M',
  }),
  def({
    id: 'rocket',
    name: 'ロケット',
    category: 'firearm',
    description: '直進ロケット弾。長押しで弾速と爆発範囲を上げる',
    press: projectile(0, 12, 20, {
      explosion: { radius: 2.0, damage: 30 },
      radius: 0.3,
      hitClass: 'heavy',
      energyPerHit: 8,
    }),
    hold: holdRelease(
      charge(
        1.0,
        projectile(0, 16, 20, {
          explosion: { radius: 3.5, damage: 50 },
          radius: 0.35,
          hitClass: 'huge',
          energyPerHit: 12,
        }),
        { damage: [30, 50], radius: [2.0, 3.5] },
      ),
    ),
    cost: { press: energy(10), hold: NONE },
    mechanisms: ['N1', 'A5'],
    scale: 'M',
  }),
  // ---- E 弓・投擲
  def({
    id: 'bow',
    name: '弓',
    category: 'ranged',
    description: '速射。長押しで狙い撃ち',
    press: hitscan(8, 14, 0.3),
    hold: holdRelease(
      charge(1.5, hitscan(15, 14, 0.5, { pierce: true, hitClass: 'medium', energyPerHit: 8 }), {
        damage: [15, 70],
      }),
    ),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['A3', 'A4'],
    scale: 'S',
  }),
  def({
    id: 'crossbow',
    name: 'クロスボウ',
    category: 'ranged',
    description: '単発。長押しで 3 連装',
    press: hitscan(18, 16, 0.8, { hitClass: 'medium' }),
    hold: holdStart(
      multihit(18, 0.15, 3, {
        ranged: { range: 16, pierce: false, beamWidth: 0 },
        hitClass: 'medium',
        energyPerHit: 3,
      }),
    ),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['A3', 'N2'],
    scale: 'M',
  }),
  def({
    id: 'shuriken',
    name: '手裏剣',
    category: 'ranged',
    description: '3 方向へ投げる。長押しで往復する大手裏剣',
    press: projectile(6, 12, 8, { count: 3, spreadDeg: 15, radius: 0.2 }),
    hold: holdStart(
      projectile(25, 12, 8, { returning: true, radius: 0.5, hitClass: 'medium', energyPerHit: 8 }),
    ),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['N1'],
    scale: 'M',
  }),
  def({
    id: 'boomerang',
    name: 'ブーメラン',
    category: 'ranged',
    description: '往復してヒット。長押しで円軌道の大回転投げ',
    press: projectile(12, 10, 8, { returning: true, radius: 0.3 }),
    hold: holdStart(
      projectile(12, 10, 4, {
        orbit: { radius: 4, turns: 3 },
        radius: 0.4,
        hitClass: 'medium',
        energyPerHit: 5,
      }),
    ),
    cost: { press: NONE, hold: stamina(15) },
    mechanisms: ['N1'],
    scale: 'M',
  }),
  def({
    id: 'throwing_knife',
    name: '投げナイフ',
    category: 'ranged',
    description: '素早い投擲。長押しで 5 本同時',
    press: projectile(8, 16, 10, { radius: 0.15, startup: 0.05, total: 0.2 }),
    hold: holdStart(projectile(6, 16, 10, { count: 5, spreadDeg: 20, radius: 0.15 })),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['N1'],
    scale: 'M',
  }),
  def({
    id: 'bomb',
    name: '爆弾',
    category: 'ranged',
    description: '放物線の爆弾。長押しで飛距離と範囲を上げる',
    press: projectile(0, 9, 8, {
      gravity: true,
      explosion: { radius: 2.0, damage: 25 },
      radius: 0.3,
      hitClass: 'heavy',
      energyPerHit: 8,
    }),
    hold: holdRelease(
      charge(
        1.0,
        projectile(0, 12, 12, {
          gravity: true,
          explosion: { radius: 3.0, damage: 25 },
          radius: 0.3,
          hitClass: 'heavy',
          energyPerHit: 8,
        }),
        { range: [4, 12], radius: [2.0, 3.0] },
      ),
    ),
    cost: { press: energy(8), hold: NONE },
    mechanisms: ['N1', 'A5'],
    scale: 'M',
  }),
  def({
    id: 'chakram',
    name: 'チャクラム',
    category: 'ranged',
    description: '貫通する円盤。長押しで壁に 2 回反射する投擲',
    press: projectile(10, 14, 9, { pierce: true, radius: 0.4 }),
    hold: holdStart(
      projectile(15, 14, 9, {
        pierce: true,
        bounces: 2,
        radius: 0.4,
        hitClass: 'medium',
        energyPerHit: 5,
      }),
    ),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['N1'],
    scale: 'M',
  }),
  def({
    id: 'sling',
    name: 'スリング',
    category: 'ranged',
    description: '石つぶて。長押しで回転させて放つ',
    press: projectile(6, 12, 8, { gravity: true, radius: 0.15 }),
    hold: holdRelease(
      charge(
        1.0,
        projectile(0, 14, 8, {
          gravity: true,
          explosion: { radius: 1.0, damage: 30 },
          radius: 0.2,
          hitClass: 'medium',
          energyPerHit: 8,
        }),
        { damage: [10, 30] },
      ),
    ),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['N1', 'A4'],
    scale: 'M',
  }),
  def({
    id: 'needle',
    name: '針',
    category: 'ranged',
    description: '貫通する細い射撃。長押しで針の雨',
    press: hitscan(3, 10, 0.1, { pierce: true, energyPerHit: 1 }),
    hold: holdStart(
      multihit(4, 0.05, 12, {
        ranged: { range: 6, pierce: true, beamWidth: 0 },
        energyPerHit: 1,
        shape: fan(6, 60),
      }),
    ),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['A3', 'N2'],
    scale: 'M',
  }),
  def({
    id: 'dart',
    name: '毒針(仮称)',
    category: 'ranged',
    description: 'ダーツ。長押しで継続ダメージの強化ダーツ',
    press: hitscan(4, 8, 0.25, { energyPerHit: 2 }),
    hold: holdStart(
      hitscan(4, 8, 0.5, {
        dot: { perSecond: 5, duration: 3 },
        hitClass: 'light',
        energyPerHit: 3,
      }),
    ),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['A3', 'N8'],
    scale: 'M',
  }),
  // ---- F 魔法風
  def({
    id: 'magic_bolt',
    name: '魔力弾',
    category: 'magic',
    description: '追尾する魔力弾。長押しで 3 発同時',
    press: projectile(10, 8, 12, { homing: true, radius: 0.3 }),
    hold: holdStart(projectile(10, 8, 12, { homing: true, count: 3, spreadDeg: 25, radius: 0.3 })),
    cost: { press: energy(3), hold: energy(9) },
    mechanisms: ['N1'],
    scale: 'M',
  }),
  def({
    id: 'magic_cannon',
    name: '魔力砲',
    category: 'magic',
    description: '魔力弾。長押しで巨大な魔力砲',
    press: projectile(8, 10, 12, { radius: 0.3 }),
    hold: holdRelease(
      charge(
        1.5,
        projectile(0, 10, 12, {
          explosion: { radius: 2.5, damage: 30 },
          radius: 0.6,
          hitClass: 'huge',
          energyPerHit: 12,
        }),
        { damage: [30, 90] },
        { moveSpeed: 0 },
      ),
    ),
    cost: { press: NONE, hold: energy(15) },
    mechanisms: ['N1', 'A4', 'A5'],
    scale: 'M',
  }),
  def({
    id: 'beam',
    name: '光線',
    category: 'magic',
    description: '細い光線。長押しで太い持続光線',
    press: hitscan(6, 12, 0.25, { pierce: true, beamWidth: 0.1 }),
    hold: holdStart(
      multihit(4, 0.1, 30, {
        whileHeld: true,
        maxDuration: 3,
        ranged: { range: 12, pierce: true, beamWidth: 0.6 },
        energyPerHit: 1,
      }),
    ),
    cost: { press: NONE, hold: energyPerSec(3) },
    mechanisms: ['A3', 'N2'],
    scale: 'M',
  }),
  def({
    id: 'meteor',
    name: '隕石',
    category: 'magic',
    description: '前方に落下物。長押しで大隕石',
    press: placed('meteor', {
      forward: 3.0,
      delay: 0.6,
      radius: 1.5,
      damage: 20,
      lifetime: 0.7,
      maxCount: 3,
    }),
    hold: holdStart(
      placed('meteor', {
        forward: 3.0,
        delay: 1.2,
        radius: 4.0,
        damage: 60,
        lifetime: 1.3,
        maxCount: 1,
        hitClass: 'huge',
        energyPerHit: 12,
      }),
    ),
    cost: { press: energy(5), hold: energy(20) },
    mechanisms: ['N3', 'A5'],
    scale: 'L',
  }),
  def({
    id: 'shockwave',
    name: '衝撃波',
    category: 'magic',
    description: '周囲のリング。長押しで広がるリング',
    press: area(12, ring(2.0, 1.0), { startup: 0.1, active: 0.1, total: 0.5, knockback: 3.0 }),
    hold: holdStart(
      area(20, ring(5.0, 1.0), {
        expandSeconds: 0.8,
        startup: 0.1,
        active: 0.8,
        total: 1.2,
        knockback: 4.0,
        hitClass: 'medium',
        energyPerHit: 8,
      }),
    ),
    cost: { press: energy(4), hold: energy(8) },
    mechanisms: ['A5'],
    scale: 'S',
  }),
  def({
    id: 'gravity',
    name: '重力球',
    category: 'magic',
    description: '前方に敵を引き寄せる球。長押しで大重力',
    press: placed('gravity', {
      forward: 4.0,
      radius: 3.0,
      lifetime: 1.5,
      damage: 5,
      interval: 1.0,
      pullSpeed: 3.0,
      maxCount: 1,
    }),
    hold: holdStart(
      placed('gravity', {
        forward: 4.0,
        radius: 5.0,
        lifetime: 3.0,
        damage: 5,
        interval: 1.0,
        pullSpeed: 4.0,
        maxCount: 1,
      }),
    ),
    cost: { press: energy(8), hold: energy(20) },
    mechanisms: ['N3', 'N9', 'N8'],
    scale: 'L',
  }),
  def({
    id: 'mirage',
    name: '分身',
    category: 'magic',
    description: '残像が斬撃を放つ。長押しで 3 体',
    press: summon('mirage', {
      count: 1,
      lifetime: 1.2,
      damage: 15,
      interval: 1.0,
      range: 2.0,
      hitClass: 'medium',
    }),
    hold: holdStart(
      summon('mirage', {
        count: 3,
        lifetime: 1.2,
        damage: 15,
        interval: 1.0,
        range: 2.0,
        hitClass: 'medium',
      }),
    ),
    cost: { press: energy(4), hold: energy(10) },
    mechanisms: ['N4'],
    scale: 'L',
  }),
  def({
    id: 'time_stop',
    name: '時間停止',
    category: 'magic',
    description: '斬撃。長押しで周囲の敵の時間を止める',
    press: combo([stage(12, 0.1, 0.1, 0.4)]),
    hold: holdStart({
      kind: 'buff',
      effect: 'timeStop',
      amount: 1.0,
      duration: 1.0,
      radius: 5.0,
      then: null,
    }),
    cost: { press: NONE, hold: energy(30) },
    mechanisms: ['A5', 'N10'],
    scale: 'M',
  }),
  def({
    id: 'magic_wall',
    name: '魔力の壁',
    category: 'magic',
    description: '前方に壁を置く。長押しで壁を押し出す',
    press: placed('wall', {
      forward: 2.0,
      radius: 1.5,
      lifetime: 2.0,
      damage: 0,
      maxCount: 1,
      blocksEnemies: true,
    }),
    hold: holdStart(
      placed('wall', {
        forward: 2.0,
        radius: 1.5,
        lifetime: 1.5,
        damage: 20,
        maxCount: 1,
        blocksEnemies: true,
        rollSpeed: 4.0,
        command: 'push',
      }),
    ),
    cost: { press: energy(15), hold: energy(5) },
    mechanisms: ['N3'],
    scale: 'L',
  }),
  def({
    id: 'blink_slash',
    name: '転移斬り',
    category: 'magic',
    description: '斬撃。長押しで敵の背後へ転移して斬る',
    press: combo([stage(12, 0.1, 0.1, 0.4)]),
    hold: holdStart(
      movement('blink', 'any', {
        distance: 3.0,
        then: combo([stage(40, 0.05, 0.1, 0.5, 0)], { hitClass: 'heavy', energyPerHit: 10 }),
      }),
    ),
    cost: { press: NONE, hold: energy(12) },
    mechanisms: ['N7', 'A2'],
    scale: 'M',
  }),
  // ---- G 設置・召喚
  def({
    id: 'mine',
    name: '地雷',
    category: 'placement',
    description: '足元に地雷を置く。長押しで全起爆',
    press: placed('mine', { radius: 1.5, damage: 30, lifetime: 10, maxCount: 3 }),
    hold: holdStart(
      placed('mine', { radius: 1.5, damage: 30, lifetime: 0, maxCount: 3, command: 'detonateAll' }),
    ),
    cost: { press: energy(8), hold: NONE },
    mechanisms: ['N3', 'A5'],
    scale: 'L',
  }),
  def({
    id: 'turret',
    name: 'タレット',
    category: 'placement',
    description: 'タレットを設置。長押しで連射強化',
    press: placed('turret', {
      forward: 1.2,
      radius: 8,
      damage: 6,
      interval: 1.0,
      lifetime: 8,
      maxCount: 1,
      hitClass: 'light',
      energyPerHit: 1,
    }),
    hold: holdStart(
      placed('turret', {
        radius: 8,
        damage: 6,
        interval: 0.5,
        lifetime: 5,
        maxCount: 1,
        command: 'boost',
        hitClass: 'light',
        energyPerHit: 1,
      }),
    ),
    cost: { press: energy(20), hold: NONE },
    mechanisms: ['N3', 'N4'],
    scale: 'L',
  }),
  def({
    id: 'familiar',
    name: '使い魔',
    category: 'placement',
    description: '追従する使い魔が攻撃。長押しで突撃',
    press: summon('familiar', { lifetime: 15, damage: 8, interval: 1.5, range: 8 }),
    hold: holdStart(
      summon('familiar', {
        lifetime: 15,
        damage: 8,
        interval: 1.5,
        range: 8,
        command: 'charge',
        commandDamage: 30,
        commandRadius: 1.5,
      }),
    ),
    cost: { press: energy(15), hold: NONE },
    mechanisms: ['N4'],
    scale: 'L',
  }),
  def({
    id: 'barrier_field',
    name: '結界',
    category: 'placement',
    description: '周囲に結界を張る。長押しで拡張',
    press: placed('field', { radius: 3.0, damage: 6, interval: 1.0, lifetime: 5, maxCount: 1 }),
    hold: holdStart(
      placed('field', { radius: 5.0, damage: 6, interval: 1.0, lifetime: 5, maxCount: 1 }),
    ),
    cost: { press: energy(20), hold: energy(10) },
    mechanisms: ['N3', 'N8'],
    scale: 'L',
  }),
  def({
    id: 'stake',
    name: '杭',
    category: 'placement',
    description: '前方に遅延発動の杭。長押しで扇形に 3 本',
    press: placed('stake', {
      forward: 2.0,
      delay: 1.0,
      radius: 1.2,
      damage: 30,
      lifetime: 1.1,
      maxCount: 3,
    }),
    hold: holdStart(
      placed('stake', {
        forward: 2.0,
        delay: 1.0,
        radius: 1.2,
        damage: 30,
        lifetime: 1.1,
        maxCount: 3,
        count: 3,
        spreadDeg: 60,
      }),
    ),
    cost: { press: energy(10), hold: energy(20) },
    mechanisms: ['N3', 'A5'],
    scale: 'L',
  }),
  def({
    id: 'missile_swarm',
    name: '誘導ミサイル',
    category: 'placement',
    description: '誘導弾 1 発。長押しで 6 発',
    press: projectile(12, 10, 14, { homing: true, radius: 0.3, hitClass: 'medium' }),
    hold: holdStart(
      projectile(10, 10, 14, { homing: true, count: 6, interval: 0.1, spreadDeg: 40, radius: 0.3 }),
    ),
    cost: { press: energy(3), hold: energy(18) },
    mechanisms: ['N1'],
    scale: 'M',
  }),
  def({
    id: 'decoy',
    name: '囮',
    category: 'placement',
    description: '囮を置いて敵を引き付ける。長押しで爆破',
    press: placed('decoy', { forward: 1.5, radius: 2.5, damage: 0, lifetime: 5, maxCount: 1 }),
    hold: holdStart(
      placed('decoy', {
        forward: 0,
        radius: 2.5,
        damage: 30,
        lifetime: 0,
        maxCount: 1,
        command: 'detonateAll',
        hitClass: 'heavy',
        energyPerHit: 8,
      }),
    ),
    cost: { press: energy(15), hold: NONE },
    mechanisms: ['N3', 'N4', 'A5'],
    scale: 'L',
  }),
  def({
    id: 'barrel',
    name: '爆発樽',
    category: 'placement',
    description: '樽を転がす。長押しで蹴り飛ばす',
    press: placed('barrel', {
      forward: 1.0,
      radius: 2.0,
      damage: 25,
      lifetime: 4,
      maxCount: 2,
      rollSpeed: 4.0,
      hitClass: 'heavy',
      energyPerHit: 8,
    }),
    hold: holdStart(
      placed('barrel', {
        forward: 1.0,
        radius: 2.0,
        damage: 25,
        lifetime: 4,
        maxCount: 2,
        rollSpeed: 10.0,
        hitClass: 'heavy',
        energyPerHit: 8,
      }),
    ),
    cost: { press: energy(10), hold: energy(10) },
    mechanisms: ['N1', 'A5'],
    scale: 'M',
  }),
  def({
    id: 'drone',
    name: 'ドローン',
    category: 'placement',
    description: '頭上のドローンが射撃。長押しで突撃して自爆',
    press: summon('drone', { lifetime: 10, damage: 5, interval: 0.5, range: 10 }),
    hold: holdStart(
      summon('drone', {
        lifetime: 10,
        damage: 5,
        interval: 0.5,
        range: 10,
        command: 'charge',
        commandDamage: 30,
        commandRadius: 2.0,
      }),
    ),
    cost: { press: energy(20), hold: NONE },
    mechanisms: ['N4'],
    scale: 'L',
  }),
  def({
    id: 'floating_swords',
    name: '浮遊剣',
    category: 'placement',
    description: '浮遊剣が順に敵へ飛ぶ。長押しで全剣同時射出',
    press: summon('swords', { count: 3, lifetime: 20, damage: 10, interval: 0.6, range: 10 }),
    hold: holdStart(
      summon('swords', {
        count: 3,
        lifetime: 20,
        damage: 10,
        interval: 0.6,
        range: 10,
        command: 'launchAll',
      }),
    ),
    cost: { press: energy(5), hold: NONE },
    mechanisms: ['N1', 'N4'],
    scale: 'L',
  }),
  // ---- H 防御・カウンター
  def({
    id: 'shield_knight',
    name: '盾騎士',
    category: 'defense',
    description: '盾殴り 2 段。長押しでガード、離すとバッシュ',
    press: combo([stage(8, 0.1, 0.1, 0.4, 0.2), stage(12, 0.12, 0.12, 0.5, 0.2)], {
      shape: sphere(1.0, 0.8),
    }),
    hold: holdStart(
      guard({
        window: 30,
        angleDeg: 120,
        reduction: 1,
        onSuccess: 'none',
        staminaPerSecond: 10,
        moveSpeed: 1.8,
        release: combo([stage(20, 0.05, 0.1, 0.4, 0.3)], { knockback: 4.0, hitClass: 'medium' }),
      }),
    ),
    cost: { press: NONE, hold: staminaPerSec(10) },
    mechanisms: ['A1', 'N5'],
    scale: 'L',
  }),
  def({
    id: 'parry',
    name: 'パリィ',
    category: 'defense',
    description: '斬撃 2 段。長押しで短いパリィ窓、成功で敵を硬直させてカウンター',
    press: combo([stage(10, 0.1, 0.1, 0.4), stage(14, 0.15, 0.15, 0.6, 0.5)]),
    hold: holdStart(
      guard({
        window: 0.3,
        onSuccess: 'counter',
        counterDamage: 45,
        toppleSeconds: 1.0,
        failRecovery: 0.5,
      }),
    ),
    cost: { press: NONE, hold: stamina(10) },
    mechanisms: ['A1', 'N5'],
    scale: 'L',
  }),
  def({
    id: 'reflector',
    name: '反射',
    category: 'defense',
    description: '打撃。長押しで反射盾(近接は半減)',
    press: combo([stage(10, 0.1, 0.1, 0.4, 0.2)]),
    hold: holdStart(guard({ window: 0.6, onSuccess: 'reflect', reduction: 0.5, counterDamage: 0 })),
    cost: { press: NONE, hold: stamina(15) },
    mechanisms: ['N5'],
    scale: 'L',
  }),
  def({
    id: 'evasive_strike',
    name: '回避撃',
    category: 'defense',
    description: '斬撃。長押しで側方へ無敵回避して斬り返す',
    press: combo([stage(10, 0.1, 0.1, 0.4)]),
    hold: holdStart(
      movement('dodge', 'any', {
        distance: 2.0,
        speed: 8,
        invincible: 0.3,
        then: lunge(30, { lungeMaxTime: 0.15, target: { halfAngleDeg: 90, range: 4 } }),
      }),
    ),
    cost: { press: NONE, hold: stamina(20) },
    mechanisms: ['N7', 'N10', 'A2'],
    scale: 'M',
  }),
  def({
    id: 'drain',
    name: '吸収',
    category: 'defense',
    description: '斬撃でヒットごとに HP 回復。長押しで大きく吸収',
    press: combo([stage(10, 0.1, 0.1, 0.4)], { heal: 2 }),
    hold: holdStart(
      combo([stage(35, 0.15, 0.15, 0.6, 0.3)], { hitClass: 'medium', energyPerHit: 10, heal: 10 }),
    ),
    cost: { press: NONE, hold: energy(10) },
    mechanisms: ['A1', 'N6'],
    scale: 'M',
  }),
  def({
    id: 'riposte_stance',
    name: '反撃姿勢',
    category: 'defense',
    description: '突き。長押しで 1 秒の反撃姿勢(被弾時に自動反撃)',
    press: combo([stage(10, 0.1, 0.1, 0.4, 0.2)], { shape: sphere(0.7, 1.5) }),
    hold: holdStart(
      guard({
        window: 1.0,
        reduction: 0,
        onSuccess: 'counter',
        counterDamage: 30,
        autoRiposte: true,
        failRecovery: 0.2,
      }),
    ),
    cost: { press: NONE, hold: stamina(15) },
    mechanisms: ['N5'],
    scale: 'L',
  }),
  def({
    id: 'iron_wall',
    name: '鉄壁',
    category: 'defense',
    description: '打撃。長押しで 2 秒間 被ダメ半減',
    press: combo([stage(12, 0.1, 0.1, 0.45, 0.2)]),
    hold: holdStart({
      kind: 'buff',
      effect: 'damageReduction',
      amount: 0.5,
      duration: 2.0,
      radius: 0,
      then: combo([stage(20, 0.1, 0.1, 0.45, 0.2)], { hitClass: 'medium' }),
    }),
    cost: { press: NONE, hold: stamina(25) },
    mechanisms: ['N10', 'A1'],
    scale: 'M',
  }),
  def({
    id: 'taunt',
    name: '挑発',
    category: 'defense',
    description: '打撃。長押しで周囲の敵を引き付け、5 秒間 攻撃力上昇',
    press: combo([stage(8, 0.1, 0.1, 0.4, 0.2)]),
    hold: holdStart({
      kind: 'buff',
      effect: 'taunt',
      amount: 0.5,
      duration: 5.0,
      radius: 8.0,
      then: null,
    }),
    cost: { press: NONE, hold: energy(10) },
    mechanisms: ['N10', 'N4'],
    scale: 'L',
  }),
  def({
    id: 'bulwark_charge',
    name: 'バリア突進',
    category: 'defense',
    description: '打撃。長押しでバリアを張って突進',
    press: combo([stage(10, 0.1, 0.1, 0.4, 0.2)]),
    hold: holdStart(
      lunge(25, {
        lungeSpeed: 10,
        lungeMaxTime: 0.4,
        target: null,
        hitWhileMoving: true,
        shape: sphere(1.0, 0.6),
        hitClass: 'medium',
      }),
    ),
    cost: { press: NONE, hold: stamina(25) },
    mechanisms: ['N5', 'A2'],
    scale: 'L',
  }),
  def({
    id: 'deflect_slash',
    name: '受け流し斬り',
    category: 'defense',
    description: '斬撃。長押しで受け流し、成功で敵を転倒',
    press: combo([stage(10, 0.1, 0.1, 0.4)]),
    hold: holdStart(
      guard({
        window: 0.4,
        onSuccess: 'topple',
        toppleSeconds: 2.0,
        counterDamage: 0,
        failRecovery: 0.3,
      }),
    ),
    cost: { press: NONE, hold: stamina(10) },
    mechanisms: ['N5', 'A1'],
    scale: 'L',
  }),
  // ---- I 移動連動
  def({
    id: 'dash_slash',
    name: 'ダッシュ斬り',
    category: 'movement',
    description: '斬撃 2 段。ダッシュ直後の長押しで突進斬り',
    press: combo([stage(10, 0.1, 0.1, 0.4), stage(12, 0.12, 0.12, 0.5)]),
    // ダッシュ直後 0.3 秒以内なら即座に突進斬り。それ以外は長押しでダッシュ(スタミナ 18)を挟む
    hold: holdStart(
      movement('dashSlash', 'any', {
        distance: 3.0,
        speed: 10,
        then: lunge(35, {
          lungeMaxTime: 0.3,
          target: null,
          hitWhileMoving: true,
          shape: sphere(1.2, 0.5),
        }),
      }),
    ),
    cost: { press: NONE, hold: stamina(15) },
    mechanisms: ['N7', 'A2'],
    scale: 'M',
  }),
  def({
    id: 'air_combo',
    name: '空中連撃',
    category: 'movement',
    description: '空中攻撃を 3 回。空中で長押しすると敵を巻き込んで着地',
    press: combo([stage(10, 0.1, 0.1, 0.4), stage(10, 0.1, 0.1, 0.4)], { airUses: 3 }),
    hold: holdStart(
      movement('airCombo', 'airborne', { then: area(25, sphere(2.0, 0), { hitClass: 'medium' }) }),
    ),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['A6', 'N7'],
    scale: 'M',
  }),
  def({
    id: 'dive',
    name: '急降下',
    category: 'movement',
    description: '斬撃。空中で長押しすると急降下して着地点に衝撃',
    press: combo([stage(10, 0.1, 0.1, 0.4)]),
    hold: holdStart(
      movement('dive', 'airborne', {
        fallSpeed: 20,
        then: area(40, sphere(2.5, 0), { hitClass: 'heavy', knockback: 5.0, energyPerHit: 10 }),
      }),
    ),
    cost: { press: NONE, hold: stamina(15) },
    mechanisms: ['N7', 'A5'],
    scale: 'M',
  }),
  def({
    id: 'glide_shot',
    name: '滑空射撃',
    category: 'movement',
    description: '射撃。滑空中に長押しで真下へ連射',
    press: hitscan(8, 12, 0.25),
    hold: holdStart(
      movement('glideShot', 'glide', {
        then: multihit(6, 0.2, 999, {
          whileHeld: true,
          maxDuration: 20,
          ranged: { range: 20, pierce: false, beamWidth: 0 },
          energyPerHit: 1,
        }),
      }),
    ),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['N7', 'A3', 'N2'],
    scale: 'M',
  }),
  def({
    id: 'wall_kick',
    name: '崖蹴り',
    category: 'movement',
    description: '打撃。崖登り中に長押しで壁を蹴って離れ、着地で衝撃',
    press: combo([stage(10, 0.1, 0.1, 0.4, 0.2)]),
    hold: holdStart(
      movement('wallKick', 'climb', {
        distance: 4.0,
        speed: 8,
        then: area(20, sphere(1.5, 0), { hitClass: 'medium' }),
      }),
    ),
    cost: { press: NONE, hold: stamina(15) },
    mechanisms: ['N7', 'A5'],
    scale: 'M',
  }),
  def({
    id: 'sliding',
    name: 'スライディング',
    category: 'movement',
    description: '打撃。スプリント中に長押しで滑り込み',
    press: combo([stage(8, 0.1, 0.1, 0.4, 0.2)]),
    hold: holdStart(
      movement('slide', 'sprint', {
        distance: 3.0,
        speed: 9,
        then: lunge(15, {
          lungeMaxTime: 0.33,
          target: null,
          hitWhileMoving: true,
          shape: sphere(0.9, 0.4),
          stunSeconds: 1.0,
          hitClass: 'medium',
        }),
      }),
    ),
    cost: { press: NONE, hold: stamina(15) },
    mechanisms: ['N7', 'A2'],
    scale: 'M',
  }),
  def({
    id: 'skate',
    name: '滑走',
    category: 'movement',
    description: '斬撃。長押し中は滑走し、離すと周囲に衝撃',
    press: combo([stage(10, 0.1, 0.1, 0.4)]),
    hold: holdStart(
      movement('skate', 'any', {
        speed: 8,
        staminaPerSecond: 10,
        then: area(25, sphere(2.0, 0), { hitClass: 'medium' }),
      }),
    ),
    cost: { press: NONE, hold: staminaPerSec(10) },
    mechanisms: ['N7', 'A5'],
    scale: 'M',
  }),
  def({
    id: 'wall_jump_strike',
    name: '壁蹴り撃',
    category: 'movement',
    description: '斬撃。壁際で長押しすると壁を蹴って上昇し落下斬り',
    press: combo([stage(10, 0.1, 0.1, 0.4)]),
    hold: holdStart(
      movement('wallJump', 'wallNear', {
        height: 3.0,
        then: area(30, sphere(1.5, 0), { hitClass: 'heavy' }),
      }),
    ),
    cost: { press: NONE, hold: stamina(20) },
    mechanisms: ['N7', 'A5'],
    scale: 'M',
  }),
  def({
    id: 'jump_slash',
    name: '跳躍斬り',
    category: 'movement',
    description: '斬撃。長押しで跳躍しながら縦斬り',
    press: combo([stage(10, 0.1, 0.1, 0.4)]),
    hold: holdStart(
      movement('jump', 'any', {
        height: 2.5,
        then: combo([stage(25, 0.05, 0.15, 0.5, 0)], { hitClass: 'medium', airUses: 1 }),
      }),
    ),
    cost: { press: NONE, hold: stamina(15) },
    mechanisms: ['N7', 'A1'],
    scale: 'M',
  }),
  def({
    id: 'sprint_ram',
    name: 'スプリント突進',
    category: 'movement',
    description: '打撃。スプリント中に長押しで加速して体当たり',
    press: combo([stage(8, 0.1, 0.1, 0.4, 0.2)]),
    hold: holdStart(
      movement('sprintRam', 'sprint', {
        speed: 9,
        distance: 4.0,
        then: lunge(25, {
          lungeSpeed: 9,
          lungeMaxTime: 0.45,
          target: null,
          hitWhileMoving: true,
          knockback: 6.0,
          shape: sphere(1.0, 0.6),
          hitClass: 'medium',
        }),
      }),
    ),
    cost: { press: NONE, hold: stamina(20) },
    mechanisms: ['N7', 'A2'],
    scale: 'M',
  }),
  // ---- J 特殊
  def({
    id: 'sonic',
    name: '音波',
    category: 'special',
    description: '周囲のリング。長押しで大音波(敵を硬直)',
    press: area(8, ring(2.0, 2.0), {
      startup: 0.1,
      active: 0.1,
      total: 0.5,
      knockback: 1.0,
      hitClass: 'light',
    }),
    hold: holdStart(
      area(15, ring(6.0, 6.0), {
        startup: 0.2,
        active: 0.1,
        total: 0.8,
        knockback: 1.0,
        hitClass: 'medium',
        stunSeconds: 1.0,
        energyPerHit: 5,
      }),
    ),
    cost: { press: energy(3), hold: energy(12) },
    mechanisms: ['A5', 'N10'],
    scale: 'M',
  }),
  def({
    id: 'self_destruct',
    name: '自爆',
    category: 'special',
    description: '打撃。長押しで周囲に大爆発(自分もダメージ)',
    press: combo([stage(10, 0.1, 0.1, 0.4, 0.2)]),
    hold: holdStart({
      kind: 'selfEffect',
      hpDelta: -30,
      minHp: 31,
      then: area(80, sphere(4.0, 0), {
        startup: 0.3,
        active: 0.1,
        total: 1.0,
        knockback: 7.0,
        hitClass: 'huge',
        energyPerHit: 0,
      }),
    }),
    cost: { press: NONE, hold: energy(50) },
    mechanisms: ['A5', 'N6'],
    scale: 'M',
  }),
  def({
    id: 'roulette',
    name: 'ランダム',
    category: 'special',
    description: '押すたびに別のスタイルの攻撃が出る',
    press: {
      kind: 'random',
      pool: ['melee', 'greatsword', 'spear', 'gun', 'boxer', 'shotgun', 'naginata', 'palm'],
    },
    hold: holdStart({
      kind: 'random',
      pool: ['melee', 'greatsword', 'spear', 'gun', 'boxer', 'shotgun', 'naginata', 'palm'],
    }),
    cost: { press: NONE, hold: NONE },
    mechanisms: [],
    scale: 'M',
  }),
  def({
    id: 'momentum',
    name: 'コンボ成長',
    category: 'special',
    description: '斬撃 3 段。ヒットするほど威力が上がる',
    press: combo([
      stage(8, 0.1, 0.1, 0.4),
      stage(8, 0.1, 0.1, 0.4),
      stage(12, 0.15, 0.15, 0.6, 0.5),
    ]),
    hold: holdStart({
      kind: 'buff',
      effect: 'momentum',
      amount: 0.1,
      duration: 2.0,
      radius: 0,
      then: null,
      maxStacks: 10,
    }),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['A1', 'N10'],
    scale: 'M',
  }),
  def({
    id: 'yoyo',
    name: 'ヨーヨー',
    category: 'special',
    description: '伸びて戻るヨーヨー。長押しで回転ヨーヨー',
    press: projectile(8, 12, 4, { returning: true, radius: 0.3 }),
    hold: holdStart(
      multihit(6, 0.25, 6, { shape: ring(2.0, 2.0), moveSpeed: 1.8, maxDuration: 1.5 }),
    ),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['N1', 'N2'],
    scale: 'M',
  }),
  def({
    id: 'giant_fist',
    name: '巨大化パンチ',
    category: 'special',
    description: '打撃。長押しで拳を巨大化して叩きつける',
    press: combo([stage(10, 0.1, 0.1, 0.4, 0.2)]),
    hold: holdRelease(
      charge(
        1.0,
        area(50, sphere(2.5, 1.5), { hitClass: 'huge', knockback: 6.0, energyPerHit: 10 }),
        { damage: [20, 50], radius: [1.2, 2.5] },
      ),
    ),
    cost: { press: NONE, hold: stamina(20) },
    mechanisms: ['A4', 'A5'],
    scale: 'S',
  }),
  def({
    id: 'fishing_rod',
    name: '釣り竿',
    category: 'special',
    description: '前方へ投げる。長押しで掛かった敵を釣り上げる',
    press: projectile(6, 12, 6, { returning: true, radius: 0.2 }),
    hold: holdStart({
      kind: 'pull',
      radius: 1.0,
      speed: 8.0,
      stopDistance: 1.0,
      holdSeconds: 0,
      reach: 6.0,
      damage: 20,
      hitClass: 'medium',
      energyPerHit: 5,
      then: null,
    }),
    cost: { press: NONE, hold: stamina(15) },
    mechanisms: ['N1', 'N9'],
    scale: 'L',
  }),
  def({
    id: 'drum',
    name: '太鼓',
    category: 'special',
    description: '打撃。拍に合わせた押下で威力 2 倍',
    press: combo([stage(8, 0.1, 0.1, 0.5, 0.2)], { comboWindow: 0.5 }),
    hold: holdStart({
      kind: 'buff',
      effect: 'rhythm',
      amount: 2.0,
      duration: 8.0,
      radius: 0,
      then: null,
      beatSeconds: 0.5,
    }),
    cost: { press: NONE, hold: NONE },
    mechanisms: ['A1', 'N10'],
    scale: 'M',
  }),
  def({
    id: 'stamina_shot',
    name: 'スタミナ弾',
    category: 'special',
    description: 'スタミナを消費して撃つ。長押しで全スタミナを弾に',
    press: hitscan(20, 10, 0.3, { hitClass: 'medium', energyPerHit: 5 }),
    hold: holdStart(
      hitscan(0, 12, 0.6, {
        pierce: true,
        hitClass: 'heavy',
        energyPerHit: 10,
        damagePerStamina: 0.8,
      }),
    ),
    cost: { press: stamina(10), hold: { type: 'allStamina' } },
    mechanisms: ['A3', 'N6'],
    scale: 'M',
  }),
  def({
    id: 'ultimate_charge',
    name: '超タメ',
    category: 'special',
    description: '斬撃。3 秒の超長押しで前方を薙ぎ払う必殺',
    press: combo([stage(10, 0.1, 0.1, 0.4)]),
    hold: holdRelease(
      charge(
        3.0,
        area(150, line(8.0, 3.0), {
          startup: 0.1,
          active: 0.15,
          total: 1.2,
          knockback: 8.0,
          hitClass: 'huge',
          energyPerHit: 0,
        }),
        { damage: [10, 150] },
        {
          moveSpeed: 0,
          tiers: [
            { seconds: 1, damage: 30 },
            { seconds: 2, damage: 80 },
            { seconds: 3, damage: 150 },
          ],
        },
      ),
    ),
    cost: { press: NONE, hold: energy(30) },
    mechanisms: ['A4', 'A3'],
    scale: 'S',
  }),
];

export const DEFAULT_ATTACK_STYLE_ID = 'melee';

const byId = new Map(ATTACK_STYLES.map((s) => [s.id, s]));

export function findAttackStyle(id: string): AttackStyleDefinition | null {
  return byId.get(id) ?? null;
}

export function defaultAttackStyle(): AttackStyleDefinition {
  const style = byId.get(DEFAULT_ATTACK_STYLE_ID);
  if (!style) throw new Error('default attack style missing');
  return style;
}
